from .orders.film import Film
from .orders.roles import Role
from .orders.review_has_film import ReviewHasFilm
from .orders.review import Review
from .orders.film_has_rating import FilmHasRating
from .orders.rating import Rating
from .orders.person import Person
from .orders.interesting_facts import InterestingFact
from .orders.genre import Genre
from .orders.extra_info import ExtraInfo
from .orders.actor import Actor
from .orders.description import Description
